module.exports = {
  TOKEN: process.env.DISCORD_TOKEN,
  OWNER_USER_ID: process.env.OWNER_USER_ID || '',
  GUILD_ID: process.env.GUILD_ID || '1481022956816830669',
  PORT: process.env.PORT || 3000,
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
  TEMPLATE_FILE: 'discord-template.json',
  CONFIG_FILE: 'brainexe-config.json',
  ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
  YOUTUBE_API_KEY: process.env.YOUTUBE_API_KEY,
  GNEWS_API_KEY: process.env.GNEWS_API_KEY,
  NEWSAPI_API_KEY: process.env.NEWSAPI_API_KEY,
  IGDB_API_KEY: process.env.IGDB_API_KEY,
  IGDB_CLIENT_ID: process.env.IGDB_CLIENT_ID,
  TAVILY_API_KEY: process.env.TAVILY_API_KEY,
  GOOGLE_CSE_API_KEY: process.env.GOOGLE_CSE_API_KEY,
  GOOGLE_CSE_CX: process.env.GOOGLE_CSE_CX,
  MONGODB_URI: process.env.MONGODB_URI,
  MIN_GAP_ANY_POST: 15 * 60 * 1000,
};
